# Generated by Django 2.2.13 on 2020-06-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170302_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, upload_to='img/users'),
        ),
    ]
