# Generated by Django 2.2.13 on 2020-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_myimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myimage',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='cars'),
        ),
    ]
